---
services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - type: volume
        source: etcd-data
        target: /etcd
        volume:
          nocopy: true
    command: "etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd"
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - type: volume
        source: minio-data
        target: /minio_data
        volume:
          nocopy: true
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    container_name: milvus
    image: milvusdb/milvus:v2.4.11
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - type: bind
        source: ./milvus/milvus.yaml
        target: /milvus/configs/milvus.yaml
      - type: volume
        source: milvus-data
        target: /var/lib/milvus
        volume:
          nocopy: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.4
    security_opt:
      - seccomp:unconfined
    environment:
      MILVUS_URL: milvus:19530
    ports:
      - "8000:7999"
    depends_on:
      - "milvus"

  redis:
    container_name: redis
    image: redis:7.4.1
    security_opt:
      - seccomp:unconfined
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis-data
        target: /data
        volume:
          nocopy: true

  jane:
    container_name: jane
    image: localhost/jane-the-llama
    security_opt:
      - seccomp:unconfined
    environment:
      JANE_REDIS_HOST: redis
      JANE_MILVUS_HOST: milvus
    ports:
      - "8001:8000"
    secrets:
      - jane_milvus_token
      - jane_watsonx_apikey
      - jane_watsonx_project_id
    depends_on:
      - milvus
      - redis

secrets:
  jane_milvus_token:
    file: ./secrets/jane_milvus_token
  jane_watsonx_apikey:
    file: ./secrets/jane_watsonx_apikey
  jane_watsonx_project_id:
    file: ./secrets/jane_watsonx_project_id

networks:
  default:
    name: jane

volumes:
  milvus-data:
  redis-data:
  etcd-data:
  minio-data:

